version: "3"

services:
  postgres:
    container_name: siscoger_postgres
    image: "postgres:9.4"
    volumes:
      - ./.docker/postgres:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
    environment:
     POSTGRES_PASSWORD: ${DB_PASSWORD}
     POSTGRES_USER: ${DB_USER}

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "16543:80"
    depends_on:
      - postgres
  # mongo:
  #   container_name: siscoger_mongo
  #   image: mongo
  #   volumes:
  #     - ./.docker/mongo:/data/db
  #   ports:
  #     - "${MONGO_PORT}:27017"

  # redis:
  #   container_name: siscoger_redis
  #   image: redis
  #   volumes:
  #     - ./.docker/redis:/redis/db
  #   ports:
  #     - "${REDIS_PORT}:6379"

