version: "3"

services:
  api:
    container_name: siscoger_api
    build:
      context: .
      dockerfile: Dockerfile    
    ports:
      - "${APP_PORT}:3000"
      - 9229:9229
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - webnet
    depends_on:
      - postgres
      - redis
      - mongo
    command: npm run start:dev

  postgres:
    container_name: siscoger_postgres
    image: "postgres:9.4"
    volumes:
      - ./.docker/postgres:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
    networks:
      - webnet
    environment:
     POSTGRES_PASSWORD: ${DB_PASSWORD}
     POSTGRES_USER: ${DB_USER}

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "16543:80"
    networks:
      - webnet
    depends_on:
      - postgres

  mongo:
    container_name: siscoger_mongo
    image: mongo
    networks:
      - webnet
    volumes:
      - ./.docker/mongo:/data/db
    ports:
      - "${MONGO_PORT}:27017"

  redis:
    container_name: siscoger_redis
    image: redis
    volumes:
      - ./.docker/redis:/redis/db
    networks:
      - webnet
    ports:
      - "${REDIS_PORT}:6379"

networks:
  webnet: