export type Iso = {
  id?: number;
  id_andamento: number;
  id_andamentocoger: number;
  sjd_ref: number;
  sjd_ref_ano: number;
  cdopm: string;
  fato_data: Date;
  abertura_data: Date;
  sintese_txt: string;
  tipo_penal: string;
  doc_tipo: string;
  doc_numero: string;
  portaria_numero: string;
  portaria_data: Date;
  exclusao_txt: string;
  opm_meta4: string;
  relatoriomedico_file: string;
  relatoriomedico_data: Date;
  solucaoautoridade_file: string;
  solucaoautoridade_data: Date;
  prioridade: number;
};
